[general]
live_config_reload = true
# 窗口设置
[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 0
y = 0

# 滚动设置
[scrolling]
history = 10000
multiplier = 3

# Colors (Gruvbox light)
# [colors.primary]
# background = '#fbf1c7'
# foreground = '#3c3836'
# [colors.normal]
# black   = '#fbf1c7'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#7c6f64'
# [colors.bright]
# black   = '#928374'
# red     = '#9d0006'
# green   = '#79740e'
# yellow  = '#b57614'
# blue    = '#076678'
# magenta = '#8f3f71'
# cyan    = '#427b58'
# white   = '#3c3836'

# Colors (Gruvbox dark)
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

# 字体设置
[font]
size = 11.25
[font.normal]
family = "JetBrainsMono Nerd Font"
# style = "Regular"
# 字符间距
[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Backslash"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt"

# 鼠标配置
[mouse]
# 打字时隐藏鼠标
hide_when_typing = true


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@="
