live_config_reload = true
# 窗口设置
[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 0
y = 0

# 滚动设置
[scrolling]
history = 10000
multiplier = 3

# gruvbox_dark Alacritty Colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'
# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'
# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

# 字体设置
[font]
size = 11.25
[font.normal]
family = "JetBrainsMono Nerd Font"
# style = "Regular"
# 字符间距
[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Backslash"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt"

# 鼠标配置
[mouse]
# 打字时隐藏鼠标
hide_when_typing = true


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@="
